name: First Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List and read file
        run: |
         echo "first gh action job"
         ls -ltra
         cat README.md 
         
      - name: Generate test file
        run: cowsay -f test "some test file read raw..." >> test.txt   

      # - name: List files
      #   run: ls

      # - name: Read file
      #   run: cat README.md    