name: First Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome message
        run: echo "first gh action job"

      - name: List files
        run: ls

      - name: Read file
        run: cat README.md    