name: Generate Ascii

on: push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsaay Program
        run: sudo apt-get install cowsay -y

      - name: Execute Cowsay CMD
        run: cowsay -f dragon "some test file read raw..." >> test.txt  
      
      - name: Upload text file
        uses: actions/upload-artifact@v3
        with:
          name: test-text-file
          path: test.txt 

  build_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
      - name: Download text file
        uses: actions/download-artifact@v3
        with:
          name: test-text-file

      - name: Test file exist
        run: grep -i "dragon" test.txt

  build_job_3:
    needs: [build_job_2]
    runs-on: ubuntu-latest
    steps:
      - name: Download text file
        uses: actions/download-artifact@v3
        with:
          name: test-text-file
          
      - name: Read file
        run: cat test.txt

      - name: Deploy
        run: echo deploying...
          

      # - name: Run Script
      #   run: |
      #     chmod +x script.sh
      #     ./script.sh         

