name: Generate Ascii

on: push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsaay Program
        uses: sudo apt-get install cowsay -y

      - name: Execute Cowsay CMD
        run: cowsay -f dragon "some test file read raw..." >> test.txt  
      
      - name: Sleep for 15 seconds
        run: sleep 15  
  build_job_2:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 5 seconds
        uses: sleep 5

      - name: Test file exist
        run: grep -i "dragon" test.txt

  build_job_3:
    runs-on: ubuntu-latest
    steps:
      - name: Read file
        uses: cat test.txt

      - name: Deploy
        run: echo deploying...
          

      # - name: Run Script
      #   run: |
      #     chmod +x script.sh
      #     ./script.sh         

